name: Non-Prod Dynatrace Configuration Backup and upload in Azure Blob storage 
'on':
    workflow_dispatch:

env:
  TF_WORKING_DIR: dt_backup/nonprod/terraform
  EXPORT_DIR: dynatrace_backup

jobs:
  dynatrace-backup:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            dt_backup/nonprod
          sparse-checkout-clone-mode: true

      - name: Install unzip
        run: |
          if ! command -v unzip >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y unzip
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Verify Terraform Version
        run: |
          terraform version

      - name: Initiate Terraform using terraform init 
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          DYNATRACE_API_URL: ${{ secrets.NP_DYNATRACE_API_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.NP_DYNATRACE_API_TOKEN }}
          DT_ACCOUNT_ID: ${{ secrets.DT_ACCOUNT_ID }}
        run: |
          terraform init

      - name: Find the terrform-provider-dynatrace executable and Export Dynatrace Configuration using terraform-provider-dynatrace
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          DYNATRACE_ENV_URL: ${{ vars.NP_DYNATRACE_API_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.NP_DYNATRACE_API_TOKEN }}
          DT_ACCOUNT_ID: ${{ secrets.DT_ACCOUNT_ID }}
        run: |
          export DYNATRACE_ENV_URL=$DYNATRACE_ENV_URL
          export DYNATRACE_API_TOKEN=$DYNATRACE_API_TOKEN
          export DT_ACCOUNT_ID=$DT_ACCOUNT_ID
          PROVIDER_BIN=$(find .terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace \
            -type f \
            -name "terraform-provider-dynatrace*" | head -n 1)
          echo "Provider Binary: $PROVIDER_BIN"
          "$PROVIDER_BIN" -export

      - name: Capture export dir and timestamp from terraform outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")
          echo "EXPORT_DIR=configuration/modules" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
         
      - name: Create Archive of the backup to upload into Azure blob
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          BACKUP_FILE="np-dynatrace-config-${TIMESTAMP}.tar.gz"
          tar -czf "$BACKUP_FILE" "$EXPORT_DIR"/*
          echo "BACKUP_FILE=$BACKUP_FILE" >> $GITHUB_ENV
          
      - name: Azure Login to upload the configuration into blob storage
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          #client-id: ${{ secrets.AZURE_CLIENT_ID }}
          #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload Configuration Backup into Azure Blob
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name dynatrace-backups \
            --name dynatracebkp/${TIMESTAMP}/${BACKUP_FILE} \
            --file ${BACKUP_FILE} \
            --auth-mode login \
            --overwrite true
